version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - apt-get update -y
      - apt-get install -y libpq-dev libzip-dev php-pgsql
      - curl -sS https://getcomposer.org/installer -o composer-setup.php
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer

  pre_build:
    commands:
      - echo "Installing PHP dependencies with Composer"
      - composer install
      - echo "Installing Node dependencies with npm"
      - npm install

artifacts:
  files:
    - "**/*"
  name: "$(date +%Y-%m-%dT%H:%M:%S).zip"
# Eliminar la sección proxy, no es estándar y puede estar causando problemas

